server:
  ssl:
    key-store: classpath:server.jks
    key-store-password: hhw0309010!
    keyStoreType: jks
    keyAlias: server_private
    enabled: true
  port: 8090

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 331153258024-lfu8v6i7m0emfrdf7retdsdlgpqa5foa.apps.googleusercontent.com
            client-secret: fjYdo01MNhrzna4JF-3o8WTn
          facebook:
            client-id: 375579863367028
            client-secret: ed43d831e5bcaaba99eb137453d1c7b8
          github:
            client-id : a8f83d7716d19a4845c2
            client-secret: e194d124119032dc9f7d359d6a138cf5c4d4ae70
          azure:
            client-id: bba52d67-3816-43a7-8d8f-69a668754a54
            client-secret: z3u5EKOsk-VQQAqV4Tf5VtLg@zYwR/F/
            authorization-grant-type: authorization_code
            scope: openid, https://graph.microsoft.com/Calendars.Read
            client-name: Azure
            provider: azure
            authorization-uri: https://login.microsoftonline.com/common/oauth2/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/token
            user-info-uri: https://login.microsoftonline.com/common/openid/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/keys

#security:
#  oauth2:
#    jwt:
#      signkey: halfdev!@$&

jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

custom:
  oauth2:
    kakao:
      client-id: 877cf350333227a753e311bd4d5b5fe6

azure:
  activedirectory:
    active-directory-groups: users
    tenant-id: d630cdb0-fb53-41f8-ba22-03399ce5b046